### PR TITLE
Feature/separation of concern

### PR DESCRIPTION
**Pull request by alex94143**
@adamos486 & @caramelqq if you like this approach, I'll apply it to other components. It's based on this article: https://blog.cloudboost.io/separate-your-code-with-styled-components-ec4fd1ee3ef8

### CODE REVIEW

**Comment by adamos486** [comment]
We've got some failing test to fix before this is mergeable.

**Comment by alex94143** [comment]
@adamos486 I only see one test failure in Results.test and it appears in master as well. Should we fix that failure first?

**Comment by adamos486** [comment]
Approved

**Review by adamos486 — APPROVED** [review]
Approved

**Pull request merged**
